name: heuristics
dependencies:
  - pip
  - python=3.9
  - ipykernel 
  - numpy=1.21
  - pytorch
  - cudatoolkit
  - numba
  - pip:
    - geopy==2.2.0
    - pytest==7.1.3
    - pandas==1.4.4
    - click==8.1.3
    - black==22.8.0
    - pylint==2.15.0

